USE [QUESTIONARIO]
GO

/* -------------------------------------------------------------------------------------------------
-- Views e Procedures
*/ -------------------------------------------------------------------------------------------------

-- --------------------------------------------------------------------------------------------
-- [QUESTIONARIO].[VW_FAMILIA_EXIBIR]
-- --------------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [QUESTIONARIO].[VW_FAMILIA_EXIBIR]
AS

/*
-- RETORNA FAMILIAS/PESSOAS
*/

	SELECT
		A.ID_FAMILIA
		,A.ENDERECO_NORMALIZADO
		,A.CDT_ENDERECO_ID_CEP
		,A.ENDERECO_NUMERO
		,A.ENDERECO_COMPLEMENTO
		,A.ENDERECO_LOGRADOURO
		,A.ENDERECO_BAIRRO
		,A.CDT_ENDERECO_ID_LOCALIDADE
		,A.FONE_FIXO
		,A.DATA_CRIACAO FAMILIA_DATA_CRIACAO
		,A.DATA_ALTERACAO FAMILIA_DATA_ALTERACAO
		,B.ID_PESSOA
		,B.CPF
		,B.NOME_COMPLETO
		,B.IDADE
		,B.SEXO
		,B.EMAIL
		,B.FONE_CELULAR
		,B.DATA_CRIACAO PESSOA_DATA_CRIACAO
		,B.DATA_ALTERACAO PESSOA_DATA_ALTERACAO
	FROM
		QUESTIONARIO.FAMILIA A (NOLOCK)
		INNER JOIN QUESTIONARIO.PESSOA B (NOLOCK)
			ON (A.ID_FAMILIA = B.ID_FAMILIA);
GO

-- --------------------------------------------------------------------------------------------
-- [QUESTIONARIO].[VW_QUESTIONARIO_OPCOES_EXIBIR]
-- --------------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [QUESTIONARIO].[VW_QUESTIONARIO_OPCOES_EXIBIR]
AS

/*
-- RETORNA QUESTIONARIOS/CATEGORIAS/TOPICOS/OPCOES ATIVOS
-- INFORMA SE SUBTOPICO
*/

	SELECT
		A.ID_INFO_SOCIAL_QUESTIONARIO
		,A.NOME QUESTIONARIO_NOME
		,A.DESCRICAO QUESTIONARIO_DESCRICAO
		,A.DATA_INICIO QUESTIONARIO_DATA_INICIO
		,A.DATA_TERMINO QUESTIONARIO_DATA_TERMINO
--		,A.ATIVO QUESTIONARIO_ATIVO
		,B.ID_INFO_SOCIAL_CATEGORIA
		,B.NOME CATEGORIA_NOME
		,B.ORDEM CATEGORIA_ORDEM
--		,B.ATIVO CATEGORIA_ATIVO
		,C.ID_INFO_SOCIAL_TOPICO
		,C.PERGUNTA TOPICO_PERGUNTA
		,C.ID_INFO_SOCIAL_RESPOSTA
		,C.RESPOSTA_OBRIGATORIA TOPICO_RESPOSTA_OBRIGATORIA
		,C.ANEXO_TOPICO_PERMITIDO TOPICO_ANEXO_TOPICO_PERMITIDO
		,C.ORDEM TOPICO_ORDEM
--		,C.ATIVO TOPICO_ATIVO
		,D.DESCRICAO RESPOSTA_DESCRICAO
		,E.ID_INFO_SOCIAL_OPCAO
		,E.OPCAO OPCAO_OPCAO
		,E.ID_INFO_SOCIAL_RESPOSTA_COMPLEMENTAR
		,E.RESPOSTA_COMPLEMENTAR_OBRIGATORIA OPCAO_RESPOSTA_COMPLEMENTAR_OBRIGATORIA
		,E.ORDEM OPCAO_ORDEM
--		,E.ATIVO OPCAO_ATIVO
		,F.DESCRICAO RESPOSTA_COMPLEMENTAR_DESCRICAO
		,(
			SELECT
				Z.ID_INFO_SOCIAL_TOPICO_PAI
			FROM
				QUESTIONARIO.INFO_SOCIAL_SUBTOPICO Z (NOLOCK)
			WHERE
				Z.ID_INFO_SOCIAL_CATEGORIA = C.ID_INFO_SOCIAL_CATEGORIA
				AND Z.ID_INFO_SOCIAL_SUBTOPICO = C.ID_INFO_SOCIAL_TOPICO
		) ID_INFO_SOCIAL_TOPICO_PAI_ABERTO
	FROM
		QUESTIONARIO.INFO_SOCIAL_QUESTIONARIO A (NOLOCK)
		INNER JOIN QUESTIONARIO.INFO_SOCIAL_CATEGORIA B (NOLOCK)
			ON (A.ID_INFO_SOCIAL_QUESTIONARIO = B.ID_INFO_SOCIAL_QUESTIONARIO)
		INNER JOIN QUESTIONARIO.INFO_SOCIAL_TOPICO C (NOLOCK)
			ON (B.ID_INFO_SOCIAL_CATEGORIA = C.ID_INFO_SOCIAL_CATEGORIA)
		INNER JOIN QUESTIONARIO.INFO_SOCIAL_RESPOSTA D (NOLOCK)
			ON (C.ID_INFO_SOCIAL_RESPOSTA = D.ID_INFO_SOCIAL_RESPOSTA)
		INNER JOIN QUESTIONARIO.INFO_SOCIAL_OPCAO E (NOLOCK)
			ON (C.ID_INFO_SOCIAL_TOPICO = E.ID_INFO_SOCIAL_TOPICO)
		INNER JOIN QUESTIONARIO.INFO_SOCIAL_RESPOSTA_COMPLEMENTAR F (NOLOCK)
			ON (E.ID_INFO_SOCIAL_RESPOSTA_COMPLEMENTAR = F.ID_INFO_SOCIAL_RESPOSTA_COMPLEMENTAR)
	WHERE
		A.ATIVO = 1
		AND B.ATIVO = 1
		AND C.ATIVO = 1
		AND E.ATIVO = 1;
GO

-- --------------------------------------------------------------------------------------------
-- [QUESTIONARIO].[VW_FOLHA_RESPOSTA_EXIBIR]
-- --------------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [QUESTIONARIO].[VW_FOLHA_RESPOSTA_EXIBIR]
AS

/*
-- RETORNA AS RESPOSTAS SALVAS
*/

	SELECT
		A.ID_INFO_SOCIAL_FOLHA_RESPOSTA
		,A.ID_PESSOA
		,A.DATA_CONFIRMACAO
		,B.RESPOSTA_COMPLEMENTAR
		,C.*
	FROM
		QUESTIONARIO.INFO_SOCIAL_FOLHA_RESPOSTA A (NOLOCK)
		INNER JOIN QUESTIONARIO.INFO_SOCIAL_RESULTADO B (NOLOCK)
			ON (A.ID_INFO_SOCIAL_FOLHA_RESPOSTA = B.ID_INFO_SOCIAL_FOLHA_RESPOSTA)
		INNER JOIN QUESTIONARIO.VW_QUESTIONARIO_OPCOES_EXIBIR C (NOLOCK)
			ON (B.ID_INFO_SOCIAL_OPCAO = C.ID_INFO_SOCIAL_OPCAO);
GO

-- --------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------