/*
-- RETORNA DE FORMA ORDENADA QUESTIONARIOS/CATEGORIAS/TOPICOS/OPCOES ATIVOS
-- INFORMA SE SUBTOPICO
*/
SELECT
	A.ID_INFO_SOCIAL_QUESTIONARIO
	,A.NOME QUESTIONARIO_NOME
	,A.DESCRICAO QUESTIONARIO_DESCRICAO
	,A.DATA_INICIO QUESTIONARIO_DATA_INICIO
	,A.DATA_TERMINO QUESTIONARIO_DATA_TERMINO
--	,A.ATIVO QUESTIONARIO_ATIVO
	,B.ID_INFO_SOCIAL_CATEGORIA
	,B.NOME CATEGORIA_NOME
	,B.ORDEM CATEGORIA_ORDEM
--	,B.ATIVO CATEGORIA_ATIVO
	,C.ID_INFO_SOCIAL_TOPICO
	,C.PERGUNTA TOPICO_PERGUNTA
	,C.ID_INFO_SOCIAL_RESPOSTA
	,C.RESPOSTA_OBRIGATORIA TOPICO_RESPOSTA_OBRIGATORIA
	,C.ANEXO_TOPICO_PERMITIDO TOPICO_ANEXO_TOPICO_PERMITIDO
	,C.ORDEM TOPICO_ORDEM
--	,C.ATIVO TOPICO_ATIVO
	,D.DESCRICAO RESPOSTA_DESCRICAO
	,E.ID_INFO_SOCIAL_OPCAO
	,E.OPCAO OPCAO_OPCAO
	,E.ID_INFO_SOCIAL_RESPOSTA_COMPLEMENTAR
	,E.RESPOSTA_COMPLEMENTAR_OBRIGATORIA OPCAO_RESPOSTA_COMPLEMENTAR_OBRIGATORIA
	,E.ORDEM OPCAO_ORDEM
--	,E.ATIVO OPCAO_ATIVO
	,F.DESCRICAO RESPOSTA_COMPLEMENTAR_DESCRICAO
	,(
		SELECT
			Z.ID_INFO_SOCIAL_TOPICO_PAI
		FROM
			QUESTIONARIO.INFO_SOCIAL_SUBTOPICO Z
		WHERE
			Z.ID_INFO_SOCIAL_CATEGORIA = C.ID_INFO_SOCIAL_CATEGORIA
			AND Z.ID_INFO_SOCIAL_SUBTOPICO = C.ID_INFO_SOCIAL_TOPICO
	) ID_INFO_SOCIAL_TOPICO_PAI_ABERTO
FROM
	QUESTIONARIO.INFO_SOCIAL_QUESTIONARIO A
	INNER JOIN QUESTIONARIO.INFO_SOCIAL_CATEGORIA B
		ON (A.ID_INFO_SOCIAL_QUESTIONARIO = B.ID_INFO_SOCIAL_QUESTIONARIO)
	INNER JOIN QUESTIONARIO.INFO_SOCIAL_TOPICO C
		ON (B.ID_INFO_SOCIAL_CATEGORIA = C.ID_INFO_SOCIAL_CATEGORIA)
	INNER JOIN QUESTIONARIO.INFO_SOCIAL_RESPOSTA D
		ON (C.ID_INFO_SOCIAL_RESPOSTA = D.ID_INFO_SOCIAL_RESPOSTA)
	INNER JOIN QUESTIONARIO.INFO_SOCIAL_OPCAO E
		ON (C.ID_INFO_SOCIAL_TOPICO = E.ID_INFO_SOCIAL_TOPICO)
	INNER JOIN QUESTIONARIO.INFO_SOCIAL_RESPOSTA_COMPLEMENTAR F
		ON (E.ID_INFO_SOCIAL_RESPOSTA_COMPLEMENTAR = F.ID_INFO_SOCIAL_RESPOSTA_COMPLEMENTAR)
WHERE
	A.ATIVO = 1
	AND B.ATIVO = 1
	AND C.ATIVO = 1
	AND E.ATIVO = 1
ORDER BY
	A.ID_INFO_SOCIAL_QUESTIONARIO
	,B.ORDEM
	,C.ORDEM;

/*
-- RETORNA POSSIVEIS ANEXOS ASSOCIADOS A UM TOPICO
-- PENDENTE JOIN COM FILEB E BUSCA DO EFETIVO ARQUIVO ARMAZENADO (VIA FILESTREAM)
*/
SELECT
	A.ID_INFO_SOCIAL_TOPICO
	,A.PERGUNTA TOPICO_PERGUNTA
	,A.ID_INFO_SOCIAL_RESPOSTA
	,A.RESPOSTA_OBRIGATORIA TOPICO_RESPOSTA_OBRIGATORIA
	,A.ANEXO_TOPICO_PERMITIDO TOPICO_ANEXO_TOPICO_PERMITIDO
	,A.ORDEM TOPICO_ORDEM
--	,A.ATIVO TOPICO_ATIVO
	,B.ID_INFO_SOCIAL_ANEXO_TOPICO
	,B.ID_PESSOA
	,B.TITULO_EXIBICAO
	,B.DATA_HORA_CRIACAO
	,C.ID_FAMILIA
	,C.CPF
	,C.NOME_COMPLETO
	,C.IDADE
	,C.SEXO
	,C.EMAIL
	,C.FONE_CELULAR
	,C.DATA_CRIACAO PESSOA_DATA_CRIACAO
	,C.DATA_ALTERACAO PESSOA_DATA_ALTERACAO
	,D.ENDERECO_NORMALIZADO
	,D.CDT_ENDERECO_ID_CEP
	,D.ENDERECO_NUMERO
	,D.ENDERECO_COMPLEMENTO
	,D.ENDERECO_LOGRADOURO
	,D.ENDERECO_BAIRRO
	,D.CDT_ENDERECO_ID_LOCALIDADE
	,D.FONE_FIXO
	,D.DATA_CRIACAO FAMILIA_DATA_CRIACAO
	,D.DATA_ALTERACAO FAMILIA_DATA_ALTERACAO
FROM
	QUESTIONARIO.INFO_SOCIAL_TOPICO A
	INNER JOIN QUESTIONARIO.INFO_SOCIAL_ANEXO_TOPICO B
		ON (A.ID_INFO_SOCIAL_TOPICO = B.ID_INFO_SOCIAL_TOPICO)
	INNER JOIN QUESTIONARIO.PESSOA C
		ON (B.ID_PESSOA = C.ID_PESSOA)
	INNER JOIN QUESTIONARIO.FAMILIA D
		ON (C.ID_FAMILIA = D.ID_FAMILIA)
WHERE
	A.ATIVO = 1
ORDER BY
	B.ID_INFO_SOCIAL_ANEXO_TOPICO;