-- ------------------------------------------------------------------
-- QUESTIONARIO.VW_QUESTIONARIO_TOPICOS_EXIBIR
SELECT
	*
FROM
	QUESTIONARIO.VW_QUESTIONARIO_TOPICOS_EXIBIR
ORDER BY
	ID_INFO_SOCIAL_QUESTIONARIO
	,CATEGORIA_ORDEM
	,TOPICO_ORDEM;
-- ------------------------------------------------------------------


-- ------------------------------------------------------------------
-- QUESTIONARIO.VW_QUESTIONARIO_OPCOES_EXIBIR
SELECT
	*
FROM
	QUESTIONARIO.VW_QUESTIONARIO_OPCOES_EXIBIR
ORDER BY
	ID_INFO_SOCIAL_QUESTIONARIO
	,CATEGORIA_ORDEM
	,TOPICO_ORDEM
	,OPCAO_ORDEM;
-- ------------------------------------------------------------------


-- ------------------------------------------------------------------
-- QUESTIONARIO.VW_FAMILIA_EXIBIR
SELECT
	*
FROM
	QUESTIONARIO.VW_FAMILIA_EXIBIR
ORDER BY
	ID_FAMILIA
	,CPF;
-- ------------------------------------------------------------------


-- ------------------------------------------------------------------
-- QUESTIONARIO.VW_FOLHA_RESPOSTA_EXIBIR
SELECT
	A.*
FROM
	QUESTIONARIO.VW_FOLHA_RESPOSTA_EXIBIR A

-- APENAS AS ULTIMAS FOLHAS PREENCHIDAS DE CADA PESSOA
WHERE
	A.ID_INFO_SOCIAL_FOLHA_RESPOSTA IN (
		SELECT TOP 1
			B.ID_INFO_SOCIAL_FOLHA_RESPOSTA
		FROM
			QUESTIONARIO.VW_FOLHA_RESPOSTA_EXIBIR B
		WHERE
			B.ID_PESSOA = A.ID_PESSOA
		GROUP BY
			B.ID_PESSOA
			,B.ID_INFO_SOCIAL_FOLHA_RESPOSTA
		ORDER BY
			B.ID_INFO_SOCIAL_FOLHA_RESPOSTA DESC
	)

ORDER BY
	A.ID_PESSOA
--	,A.ID_INFO_SOCIAL_FOLHA_RESPOSTA DESC
	,A.ID_INFO_SOCIAL_QUESTIONARIO
	,A.CATEGORIA_ORDEM
	,A.TOPICO_ORDEM
	,A.OPCAO_ORDEM;
-- ------------------------------------------------------------------


-- ------------------------------------------------------------------
-- QUESTIONARIO.VW_ANEXO_TOPICO_EXIBIR
SELECT
	A.*
FROM
	QUESTIONARIO.VW_ANEXO_TOPICO_EXIBIR A

-- APENAS OS ANEXOS DAS ULTIMAS FOLHAS PREENCHIDAS DE CADA PESSOA
WHERE
	A.ID_INFO_SOCIAL_FOLHA_RESPOSTA IN (
		SELECT TOP 1
			B.ID_INFO_SOCIAL_FOLHA_RESPOSTA
		FROM
			QUESTIONARIO.VW_ANEXO_TOPICO_EXIBIR B
		WHERE
			B.ID_PESSOA = A.ID_PESSOA
		GROUP BY
			B.ID_PESSOA
			,B.ID_INFO_SOCIAL_FOLHA_RESPOSTA
		ORDER BY
			B.ID_INFO_SOCIAL_FOLHA_RESPOSTA DESC
	)

ORDER BY
	A.ID_PESSOA
--	,A.ID_INFO_SOCIAL_FOLHA_RESPOSTA DESC
	,A.ID_INFO_SOCIAL_QUESTIONARIO
	,A.CATEGORIA_ORDEM
	,A.TOPICO_ORDEM;
-- ------------------------------------------------------------------