-- QUESTIONARIO.VW_QUESTIONARIO_EXIBIR
SELECT
	*
FROM
	QUESTIONARIO.VW_QUESTIONARIO_EXIBIR
ORDER BY
	ID_INFO_SOCIAL_QUESTIONARIO
	,CATEGORIA_ORDEM
	,TOPICO_ORDEM
	,OPCAO_ORDEM;


-- QUESTIONARIO.VW_FAMILIA_EXIBIR
SELECT
	*
FROM
	QUESTIONARIO.VW_FAMILIA_EXIBIR
ORDER BY
	ID_FAMILIA
	,CPF;


-- QUESTIONARIO.VW_FOLHA_RESPOSTA_EXIBIR
SELECT
	*
FROM
	QUESTIONARIO.VW_FOLHA_RESPOSTA_EXIBIR
ORDER BY
	ID_PESSOA
	,ID_INFO_SOCIAL_FOLHA_RESPOSTA
	,ID_INFO_SOCIAL_QUESTIONARIO
	,CATEGORIA_ORDEM
	,TOPICO_ORDEM
	,OPCAO_ORDEM;